### ISSUE TITLE
Bug: Make/Build Failure on Linux With 2.15.0.5 [Makefile:764: longbits.h] Error 1

### ISSUE THREAD

**Issue by LAP6282** [lcn2/calc#145] opened 2024-04-02 16:30 UTC
Attempting to build 2.15.0.5 on Linux by running make causes this error.  The complete make output is shown:

[calc-2.15.0.5]# make
forming have_ban_pragma.h
have_ban_pragma.h formed
forming have_const.h
have_const.h formed
forming have_stdbool.h
have_stdbool.h formed
forming have_string.h
have_string.h formed
forming have_newstr.h
have_newstr.h formed
forming have_memmv.h
have_memmv.h formed
forming have_stdlib.h
have_stdlib.h formed
forming have_unistd.h
have_unistd.h formed
forming endian_calc.h
endian_calc.h formed
forming have_limits.h
have_limits.h formed
forming charbit.h
make: [Makefile:728: charbit.h] Error 127 (ignored)
charbit.h formed
forming longbits.h
make: *** [Makefile:764: longbits.h] Error 1

This error does not occur on calc-2.14.3.5 which is the previous version that I have built successfully.

uname -a:
Linux 6.8.1 #1 SMP Fri Mar 15 16:04:06 EDT 2024 x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux

Make version: 4.4.1

Bash version: 5.2_p26

I have found a similar issue reported with MacOS:

https://trac.macports.org/ticket/67833

**Comment by lcn2** [comment] 2024-04-02 16:45
Thank you @LAP6282 for the bug report. 

Please run `make clobber debug` and attach the `debug.out` file to this issue.

**Comment by LAP6282** [comment] 2024-04-02 17:21
Running "make clobber debug" actually successfully built the calc executable and libraries.

I then unpacked the 2.15.05 source and ran "make clobber all."  The executable and libraries were successfully built and passed all tests.

Possibly, there were some environmental variables set on my system that interfered with my initial build.

From now on I will start a new terminal and use "make clobber all."

**Comment by lcn2** [comment] 2024-04-02 19:06
We recommend `make clobber all chk`. 

Adding the `chk` runs the extensive regression test suite.  You can substitute `check` for `chk` if you like verbosity.  We prefer `chk` because, while much less verbose, will print any errors in context should they occur.

**Comment by lcn2** [comment] 2024-04-02 19:09
Perhaps this feedback should be provided to the Mac ports folks? I don't know if they were suffering from the same problem of trying to build from a source and/or environment that's unclean.

There was a reference to a power PC problem earlier in the Mac ports issue from an earlier version of calc.  That  issue was fixed when we ported Calc to the IBM mainframe.

**Comment by lcn2** [comment] 2024-04-02 19:09
# QUESTION 

Should we close this bug? We do appreciate the report, but it sounds like you have fixed the problem. Please advise.

**Comment by LAP6282** [comment] 2024-04-02 19:26
On Tue, 02 Apr 2024 12:10:20 -0700
Landon Curt Noll ***@***.***> wrote:

> 
> Should we close this bug? We do appreciate the report, but it sounds
> like you have fixed the problem. Please advise. 
> 

Yes, please close.

**Closed** 2024-04-03 06:31 UTC
Labels: bug

**Comment by lcn2** [comment] 2024-04-03 06:32
Thank you @LAP6282 and best wishes.
